import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Card from './Card';
import NavBar from './NavBar';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/weather.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main className={styles.main_div} style={{ 
        backgroundImage: `url(/screen-12.jpg)`,backgroundRepeat: 'no-repeat',backgroundSize: `cover`
      }}>
        <div className={styles.wrap}>
            <NavBar/>
            <h1 className="relative bottom-32 left-28 text-5xl"><i>Current Weather</i></h1>
            <Card />
            <p className='relative left-20 bottom-16'><b>-- Weather APP | Powered by React | <i>Developed by Somak Poddar💖💖</i> --</b></p>
        </div>
      </main>

    </>
  )
}
